---
- name: Check if couchdb is created
  become: yes
  uri:
    url: http://127.0.0.1:5984


- debug:
    msg: "Couchdb is established"



- name: create a database "tweets"
  become: yes
  uri:
    url: http://{{couchdb_user}}:{{couchdb_password}}@localhost:5984/tweets
    method: PUT
    force_basic_auth: yes
    status_code: 201,412




- debug:
    msg: "A database called tweets is created"



- name: Copy design.json from local to remote hosts
  become: yes
  copy:
    src: design.json
    dest: /home/ubuntu/
    mode: u=rw

- name: Copy streaming_to_couchdb.py from local to remote hosts
  become: yes
  copy:
    src: streaming_to_couchdb.py
    dest: /home/ubuntu/
    mode: u=rw


- name: Create clean_tweet_by_search design document
  become: yes
  shell: curl -X PUT http://{{ couchdb_user }}:{{ couchdb_password }}@127.0.0.1:5984/clean_tweet_by_search/_design/language --data-binary @design.json

- name: Create vulgar_tweet_by_search design document
  become: yes
  shell: curl -X PUT http://{{ couchdb_user }}:{{ couchdb_password }}@127.0.0.1:5984/vulgar_tweet_by_search/_design/language --data-binary @design.json










